### PR TITLE
Documentation fixes in Bayesian network recipie

### PR DESCRIPTION
**Pull request by andreasdoll**

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Thanks for the PR! Please replicate these fixes in the `md` and `ipynb` files too.

**Comment by andreasdoll** [comment]
@fchollet Added another fix and replicated all changes in notebook and markdown files

**Comment by fchollet** [comment]
Thanks! You'll also need to sign the CLA: https://cla.developers.google.com/clas

**Comment by pcoet** [comment]
Thanks for the PR, @andreasdoll. Are you planning to sign the CLA? After you do that, we can merge this. Otherwise, if we don't hear from you, we'll close the request.

**Pull request closed without merging**
