### PR TITLE
Added huggingface model and spaces links for CTC-ASR example

### PR DESCRIPTION
**Pull request by anuragshas**
As per the ongoing huggingface keras sprint, have updated the CTC-ASR example python file.
@rushic24 please help in generating the ipynb and markdown for this example

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by fchollet** [comment]
> Failing after 1s — ❌ Missing CLA from one or more contributors

Please sign the CLA.

**Comment by anuragshas** [comment]
I have signed CLA on 16th July

**Comment by anuragshas** [comment]
I have signed CLA on 16th of July

**Comment by fchollet** [comment]
Thanks for the contribution!

**Pull request merged**
