### PR TITLE
Fix Bug

### PR DESCRIPTION
**Pull request by theDreamer911**
Fixing error in image Path of Vision/md section

### CODE REVIEW

**Comment by fchollet** [comment]
Please rebase the PR -- it should be touching 3 files, not 375.

**Comment by theDreamer911** [comment]
> Please rebase the PR -- it should be touching 3 files, not 375.

Alright, but I just realize that all picture in `md` document is broken, because it direct into the wrong directory. Is it fine for me to only fix three of them?

**Comment by fchollet** [comment]
?

**Comment by theDreamer911** [comment]
> ?

Here is before
image

---
and here is after
image

---
The problem come because all local images in `md` files direct into this directory 

```
    /img/examples/vision/
```

I just want to fix it, thanks

**Comment by fchollet** [comment]
Maybe you're building from an incorrect location? See instructions in the README

**Comment by theDreamer911** [comment]
Sir, I'm sorry for not being polite. Will you accept my PR if I only fix 3 of the file?

I just want to make sure all documentation works perfectly. I'm sorry for making such mistake. If you have time, I want to ask you to open documents such as

[here](https://github.com/keras-team/keras-io/blob/master/examples/vision/md/3D_image_classification.md)

or 

[here](https://github.com/keras-team/keras-io/blob/master/examples/vision/md/image_classification_efficientnet_fine_tuning.md)

And I bet you will see a broken picture because it directs into a non-existing directory. Again, I'm sorry for not being polite.

BTW,
Thanks for your code review

**Pull request closed without merging**
