### PR TITLE
Add instructions to install tfsim from pypi.

### PR DESCRIPTION
**Pull request by owenvallis**
Currently, running the example using Colab will fail when tfsim is not installed. This PR adds instructions for installing tfsim from pypi.

### CODE REVIEW

**Comment by owenvallis** [comment]
Not sure why the PR pulled in the older commits (maybe because they were squashed when we merged last time). This is just a small change to make it easier to install tfsim when running the example notebook on Colab.

**Comment by owenvallis** [comment]
Looks like the black formatter doesn't allow the `!pip install tensorflow_similarity` line. Is there a preferred way to handle install deps in the examples?

**Review by fchollet — COMMENTED** [review]
Thanks for the PR! Everything looks good, please also update the `md` and `ipynb` files.

**Comment by owenvallis** [comment]
Thanks! Should be good to go now.

**Review by fchollet — APPROVED** [review]
LGTM, thank you

**Pull request merged**
