### PR TITLE
Fixes keras-team/keras-io#420

### PR DESCRIPTION
**Pull request by B-Deforce**
Added call method in the VAE class solving issue keras-team#420

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR. This change seems fine, but it isn't necessary in order to run the example. You can just run the existing code without modifications, e.g. here https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/generative/ipynb/vae.ipynb

**Comment by B-Deforce** [comment]
Interesting. It indeed runs in the Google Colab-link you sent. Regardless, I ran into the same issue as #420 when running it locally.  However, I'm using tf-nightly (2.7.0) so this might be the reason. Since it works in Colab, I assume this PR can be closed?

**Comment by fchollet** [comment]
I verified it works with TF 2.7.

Please try printing `tf.__version__` in your local failing script and let me know. I'm guessing there's something wrong with your environment.

**Comment by B-Deforce** [comment]
This returns '2.7.0-dev20210722'. I guess it must indeed be an issue in my environment somewhere. I've included the error-log just as a reference. 
[error_log.txt](https://github.com/keras-team/keras-io/files/6900902/error_log.txt)

**Comment by fchollet** [comment]
Did you modify the example in any way?

**Comment by B-Deforce** [comment]
Apologies for the delay in response. I have potentially found the issue by indeed checking the small modifications I added to my own code. The error mentioned in #420 seems to arise when using an `ImageDataGenerator` (since I'm using `flow_from_directory` to load the data). The example from `vae.py` just loads MNIST as a `np.ndarray` which does not throw an error. If I take a subset from the `DirectoryIterator` (which yields a `np.ndarray`) there is no error which would prove the `DirectoryIterator` is indeed the cause of the error. However, the strange thing is that the error disappears if I just call fit for a second time in a row on the `DirectoryIterator`, which does not really make sense. I have added a screen recording of this strange behavior to clarify.


https://user-images.githubusercontent.com/72612139/127980688-abd4f918-7e28-46af-b5df-677bfb630b69.mp4

**Comment by fchollet** [comment]
When you pass a generator to an unbuilt subclassed model, it will try to call the model to build it:

```python
    # Need to build the Model on concrete input shapes.
    if model is not None and not model.built:
      concrete_x, _, _ = unpack_x_y_sample_weight(peek)
      model.distribute_strategy.run(
          lambda x: model(x, training=False), args=(concrete_x,))
```

(it works the 2nd time because by then the model is built)

> since I'm using flow_from_directory to load the data

Just use https://keras.io/api/preprocessing/image/#imagedatasetfromdirectory-function

**Comment by fchollet** [comment]
An update: the step of calling the model to create the weights only made sense for models that actually have a forward pass of their own. I added a change to skip this step when `call` is not implemented. So now you should not see the issue anymore, even with the Python generator. https://github.com/keras-team/keras/commit/d9abcd788e5419560c4d8bd47b22ec387fe5c9c2

FYI the reason we have to do this for Python generators but not for other types of inputs is a technicality. All inputs are converted to tf.data.Dataset objects, but Datasets created from generators don't have a defined shape, unfortunately. Normally we create the model state during compilation, but this requires the dataset to have a known shape. So for generator inputs we have to use a concrete batch of data to call the model before we convert the generator to a Dataset.

In general always prefer using NumPy arrays or Dataset objects rather than generators. It will be more performant anyway.

**Comment by B-Deforce** [comment]
Great, I tried it and it indeed works now without `call` being implemented. Thanks for the interesting insights!

**Pull request closed without merging**
