### PR TITLE
Update handwriting_recognition.py

### PR DESCRIPTION
**Pull request by jpweijers**
Added missing `e` in provides.

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the PR! Please fix the typo in the corresponding `md` and `ipynb` files as well.

**Comment by jpweijers** [comment]
I've fixed the other two files as well now 🙂

**Comment by fchollet** [comment]
Thanks! Before we can merge the PR, you'll need to sign the CLA as well: https://cla.developers.google.com/clas

**Comment by jpweijers** [comment]
CLA is signed

**Pull request merged**
