### PR TITLE
Updated Timeseries forecasting example to Work in Progress

### PR DESCRIPTION
**Pull request by yashika51**
### Updated the **Timeseries forecasting with LSTM for weather prediction** example to work in progress. 

My team through MLH fellowship is working on this example as mentioned in issue #102. This pull request updates the [contribution guide](https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md) with work in progress for this example.

### CODE REVIEW

**Comment by fchollet** [comment]
Please clean up the staged files and the commit history.

**Comment by PrabhanshuAttri** [comment]
@fchollet definitely. When you say staged files, do you mean .gitignore?

**Comment by yashika51** [comment]
Sure, we'll also add the organized and final code along soon.

**Comment by fchollet** [comment]
The commit history has 14 commits and the PR size is +423,226 lines. Please rebase to master.

**Comment by PrabhanshuAttri** [comment]
Sure, I think that are so many additions due to the addition of `jena_climate_2009_2016.csv`. We can remove that.

**Comment by fchollet** [comment]
Data files should be downloaded from the web rather than included in the repo.

**Comment by jcbank** [comment]
오늘 가입했어요.많이 배우도록 할게요.

**Comment by yashika51** [comment]
We have submitted an updated PR #123. 
Closing this PR.

**Pull request closed without merging**
