### PR TITLE
Adding Temporal Latent Bottleneck

### LINKED ISSUE #1257: Add example: Temporal Latent Bottleneck
Me and @suvadityamuk are trying to implement [Temporal Latent Bottleneck: Synthesis of Fast and Slow Processing Mechanisms in Sequence Learning](https://arxiv.org/abs/2205.14794) in Keras. We have a working baseline on image classification with the Slow and Fast stream learning as suggested in the paper.

We would love for our implementation to be part of the keras examples.

CC: @fchollet

### PR DESCRIPTION
**Pull request by ariG23498**
This PR adds a minimal implementation of [Temporal Latent Bottleneck: Synthesis of Fast and Slow Processing Mechanisms in Sequence Learning](https://arxiv.org/abs/2205.14794)

[Colab Notebook](https://arxiv.org/abs/2205.14794)

Closes #1257 

CC: @suvadityamuk

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the PR!

**Review by fchollet — COMMENTED** [review]
Thanks for the updates, and sorry for the delay in reviewing. I applied some copyedits, please pull them first. You can add the generated files!

**Comment by ariG23498** [comment]
@fchollet I have generated the files!

The CI for `docker-image` fails. I think it is due to the version mismatch of TensorFlow. I see that in the `requirements.txt` the version of TensorFlow is `2.11.0`. I think this CI fail should be adressed in a seperate PR. WDYT?

**Review by fchollet — APPROVED** [review]
CI should be fixed now. Thank you for the contribution!

**Pull request merged**
