### PR TITLE
Correct description of logs on batch end

### PR DESCRIPTION
**Pull request by lifetheater57**
Of what I understand of the code, and it's coherent with the output 
in the current file, is that the loss value in the logs of the 
funciton `on_epoch_end` is that of the last step of the epoch rather 
than the mean of the losses of its steps.

I guess the intention what to return the average loss of the epoch's
steps. However, since it's not what was implemented the documentation
shouldn't be misleading.

### CODE REVIEW

**Comment by lifetheater57** [comment]
@googlebot I signed it!

**Comment by MarkDaoust** [comment]
Yes, in that example code, the loss value seen by the `on_epoch_end` is the same value seen by by the last `on_batch_end`.

But the values getting passed to `on_batch _end` are the metric outputs, typically these are the average so far this epoch.

Feel free to verify. But the reasons I'm sure about this are:

1.  If you remove the `verbose=0` you'll see the fit progress bar. It shouw the same numbers, and I know this fit bar shows the average so far this epoch.
2. Look at this code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L814

IIUC: If you pass a simple function as a metric keras automatically wraps it up in a `Mean` metric.

I think if you want to see batch logs you need to write a custom metric class that doesn't accumulate over the epoch.


So I think the fix here may be: either better explain that the batch loss is the loss so far this epoch, or implement that custom batch metric wrapper.

Right?

**Comment by fchollet** [comment]
As Mark pointed out, the statement is already correct. By default `on_epoch_end` gives you the output of `metric.result()` for each model metric (including the loss tracker), which corresponds to the average of the metric(s) over the epoch.

We should actually clarify the other statements, `on_train_batch_end` and `on_test_batch_end`. They make it sound like the loss reported is the one on the last batch, but it's actually the current `metric.result()` value at that batch, which is the average of the loss for all the batches seen since the start of the epoch (or since the start of evaluation). Please update the PR.

**Comment by fchollet** [comment]
Are you still working on this PR?

**Comment by lifetheater57** [comment]
I went for an edit of the text in the prints. Alternatively, the additional details could have been added in the description preceding the  callback class definition.

**Review by fchollet — APPROVED** [review]
LGTM, please update the autogenerated files (`python autogen.py add_guide writing_your_own_callbacks`)

**Comment by lifetheater57** [comment]
I did it. 

However, I would like to preview the results and I cannot since I get `FileNotFoundError: [Errno 2] No such file or directory: '../templates/guides/keras_tuner/custom_tuner.md'` when executing `python autogen.py make`. I tried it on my `patch-2` as well as the `master` branch.

**Comment by MarkDaoust** [comment]
> `python autogen.py add_guide writing_your_own_callbacks`

> `FileNotFoundError: [Errno 2] No such file or directory: '../templates/guides/keras_tuner/custom_tuner.md'`

Are you running it from inside the scripts directory?

**Comment by lifetheater57** [comment]
Yes, I'm running it from the scripts directory.

**Comment by fchollet** [comment]
You need to merge master into your branch. If all else fails, start from a fresh clone.

**Comment by lifetheater57** [comment]
I already tried both after checkout the master branch from my working clone and after checkout the master branch from a fresh clone. `python autogen.py make` also failed in those cases.

Are there any additional requirements needed for this operation?

**Comment by fchollet** [comment]
> after checkout the master branch from a fresh clone

I can't reproduce that, it definitely works fine with a fresh clone.

**Comment by lifetheater57** [comment]
It works on the master branch of the main repo but not on the master branch of my fork, my bad.

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Pull request merged**
