### PR TITLE
Issue 1507

### PR DESCRIPTION
**Pull request by Zekrom-7780**
## Description

This pull request addresses the issue outlined in Issue #1507 .

## Changes Made

- Added successfully the changes requested by @hertschuh, in the previous Pull request (that I panicked and closed)

## P.S.

So Sorry for creating a New pull request, as in the process of squashing the commits, I accidently got even more commits, and I didn't end up squash them at all.

cc @hertschuh @sachinprasadhs

### CODE REVIEW

**Comment by hertschuh** [comment]
@Zekrom-7780 , thanks for the new PR. In the process of changing PRs, you lost the part about using `scaled_batch_size `. Can you re-add that?

**Comment by Zekrom-7780** [comment]
@hertschuh , added

**Comment by hertschuh** [comment]
> @hertschuh , added
> 
> Also how do I format it? Like in keras-cv, we have `format.sh` and `lint.sh`, but here I couldn't find anything

Thanks! You can use black directly: `black examples/nlp/data_parallel_training_with_keras_nlp.py`

**Review by hertschuh — APPROVED** [review]
Thanks for the updated PR!

**Comment by Zekrom-7780** [comment]
Ran `black examples/nlp/data_parallel_training_with_keras_nlp.py`, in the latest commit

**Review by hertschuh — APPROVED** [review]
Thanks!

**Comment by Zekrom-7780** [comment]
@hertschuh , are there any other issues that I can work on?
Also here, should I change the date of updation and the name?

**Comment by hertschuh** [comment]
@fchollet can you merge this change? Thanks!

**Review by sachinprasadhs — APPROVED** [review]

**Pull request merged**
