### PR TITLE
Update cct.py

### PR DESCRIPTION
**Pull request by Shreyas-Bhat**
Correct spelling 'of'

### CODE REVIEW

**Comment by Shreyas-Bhat** [comment]
> @googlebot I signed it!

**Review by fchollet — CHANGES_REQUESTED** [review]
Thanks for the PR! Please replicate the change in the `md` and `ipynb` files.

**Comment by Shreyas-Bhat** [comment]
> Thanks for the PR! Please replicate the change in the `md` and `ipynb` files.

Hello! I have made the changes in the respective files. Please accept the changes
Thank you

**Comment by fchollet** [comment]
Thanks for the update. Please bring all of the 3 changes in a single PR.

**Comment by Shreyas-Bhat** [comment]
> Thanks for the update. Please bring all of the 3 changes in a single PR.

Hello, I have made the changes in all the 3 files in a single PR
Thank you!

**Pull request closed without merging**
