### PR TITLE
Create samplersv1.py

### PR DESCRIPTION
**Pull request by ushareng**
Sampling Discussion using KerasNLP

Colab Notebook : https://colab.research.google.com/drive/13ZjB-skKvRtS3IXbFaTdnk4pSbHHNwpV?usp=sharing

@martin-gorner @mattdangerw @jbischof

### CODE REVIEW

**Comment by sachinprasadhs** [comment]
@ushareng , Could you please follow the link https://cla.developers.google.com/. and sign a Contributor License Agreement (CLA)

**Comment by ushareng** [comment]
> @ushareng , Could you please follow the link https://cla.developers.google.com/. and sign a Contributor License Agreement (CLA)

image

I signed the agreement yesterday

**Comment by haifeng-jin** [comment]
@mattdangerw Would you please help take a look at this PR? Thanks!

**Comment by sachinprasadhs** [comment]
Hi @ushareng , Could you please ensure you follow the steps [here](https://github.com/keras-team/keras-io/pull/1462/checks?check_run_id=16186397462) and make sure the `cla/google` is passing, we will be able to proceed further only after `cla/google` is cleared.
Your other [PR](https://github.com/keras-team/keras-io/pull/1464) will be cleared once the above linked steps are followed.

**Pull request closed without merging**
