### PR TITLE
update text_classification_with_transformer code example more underst…

### PR DESCRIPTION
**Pull request by d0r1h**
Adding argument name [optimizer and loss] in compile method of Keras.…andable

### CODE REVIEW

**Comment by d0r1h** [comment]
@googlebot I signed it!

**Review by fchollet — COMMENTED** [review]
Looks good, thanks! Please replicate the one-line fix in the ipynb and md files.

**Comment by d0r1h** [comment]
Thanx, I have updated and have created a pull request.

**Comment by d0r1h** [comment]
Thanx, I have updated the code for ipynb and md [files]

**Review by fchollet — APPROVED** [review]

**Comment by fchollet** [comment]
Please fix the `black` formatting of the file.

**Comment by d0r1h** [comment]
I have fixed the **black** formatting of the file, Thanks.

**Pull request merged**
