### PR TITLE
Update KerasCV block

### PR DESCRIPTION
**Pull request by LukeWood**

### CODE REVIEW

**Comment by tanzhenyu** [comment]
Oh I already merged the above PR, so the merging is currently blocked?

**Comment by LukeWood** [comment]
> Oh I already merged the above PR, so the merging is currently blocked?

This is Keras.io

**Review by tanzhenyu — APPROVED** [review]
Thanks!

**Comment by tanzhenyu** [comment]
> > Oh I already merged the above PR, so the merging is currently blocked?
> 
> This is Keras.io - I think we need 1 approval.

Got it. It doesn't look like I have the write access

**Review by fchollet — APPROVED** [review]

**Pull request merged**
