### PR TITLE
Fixing typos in Keras-NLP getting started guide

### PR DESCRIPTION
**Pull request by haifeng-jin**
Please check if the new link to pretraining guide is correct.
The old one is broken.

Do not merge before regenerating the md and ipynb files.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thank you for the fixes! Can you regenerate the ipynb/md files as well?

**Comment by fchollet** [comment]
BTW the link (https://keras.io/guides/keras_nlp/transformer_pretraining/#pretraining) works fine.

**Comment by jbischof** [comment]
Looks great!

Can you do me one favor and change the Author line to 
```
Author: [Jonathan Bischof](https://github.com/jbischof)
```

Thanks!

**Review by jbischof — APPROVED** [review]

**Comment by haifeng-jin** [comment]
All done. Ready to be merged.
Some additional changes appeared in the generated files (.ipynb and .md) that was not from this PR's change of the .py file.
They are from previous merged PRs.

**Review by fchollet — APPROVED** [review]
Thank you!

**Pull request merged**
