### PR TITLE
[Video_classification example] dimension call is fixed / variable typo is fixed

### PR DESCRIPTION
**Pull request by LeeChanHyuk**
I found some issues in the 'video_classification' example.

1. variable name is changed.  [temp_frame_featutes, frame_featutes] -> [temp_frame_features, frame_features]

2. dimension call is changed. shape of 'batch' is [frame_count, height, width, channel]. So 'video_length' must be 'batch[0]'

And I changed 'py', 'ipynb', 'md' for 'video_classification' example. But 'ipynb' doesn't run again because the things that I changed don't affect about the result.

### CODE REVIEW

**Comment by LeeChanHyuk** [comment]
@googlebot I signed it!

**Comment by fchollet** [comment]
> But 'ipynb' doesn't run again because the things that I changed don't affect about the result.

What do you mean? What's the issue?

**Comment by fchollet** [comment]
+ @sayakpaul please take a look

**Comment by sayakpaul** [comment]
Thanks for the fixes @LeeChanHyuk!

You are totally right that `batch.shape[0]` should have been used to compute the length of a given video. In this particular example, that did not matter since all the videos were capped to `MAX_SEQ_LENGTH` (`batch.shapes[1]` always produces 128). Hence I could not immediately spot it. Thank you for your time in fixing this!

Would you mind correcting the [Video Transformers](https://keras.io/examples/vision/video_transformers/) example as well? 

Also, when you are submitting PR prefer to only include the Python script. Once the PR is approved then you can add the generated files as per the [guidelines](https://github.com/keras-team/keras-io#creating-a-new-example-starting-from-a-ipynb-file). 

Let me know if anything is unclear.

**Comment by LeeChanHyuk** [comment]
@fchollet 
First, thank you for your comment and sorry for the insufficient explanation.
I was writing a comment about your question, but I'm glad that @sayakpaul understood it well.

@sayakpaul 
Thank you for your comment. I'm glad my work was helpful for your code!
Then, should I include only 'python script' in the current commit, delete the rest, and follow the procedure of adding the rest of the files after merging?

And like you said, I would like to incorporate the 'Video transformer' example if possible, but can I do a new PR myself for the 'Video transformer' myself?

**Comment by sayakpaul** [comment]
> Thank you for your comment. I'm glad my work was helpful for your code!
Then, should I include only 'python script' in the current commit, delete the rest, and follow the procedure of adding the rest of the files after merging?

Yes, it should be done when the PR is approved. So before merging all the files will be present. 

> And like you said, I would like to incorporate the 'Video transformer' example if possible, but can I do a new PR myself for the 'Video transformer' myself?

Yes. Please prefer a new PR for that.

**Comment by LeeChanHyuk** [comment]
Thanks for your reply. I delete my 'ipynb' and 'md' file in my files. please check about that.
And I will add 'ipynb' and 'md' files according to the guideline after approval.

**Review by fchollet — APPROVED** [review]
The change looks good to me -- if that's everything, then you can also update the md and ipynb files. Thanks!

**Comment by LeeChanHyuk** [comment]
I regenerated the 'ipynb' and 'md' file according to the guidelines of Keras and updated the files.
If some issue is occurred, please let me know. Thanks!

**Review by fchollet — APPROVED** [review]
Thank you!

**Pull request merged**
