### PR TITLE
Minor spelling and grammar changes

### PR DESCRIPTION
**Pull request by numbleroot**

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
These changes all look correct to me. 

Can you please regenerate the notebook and markdown files. I believe the command is:

```
cd scripts/
python autogen.py add_guide serialization_and_saving
```

**Comment by fchollet** [comment]
Thanks for the PR. You need to sign the CLA first: https://cla.developers.google.com/clas

**Comment by fchollet** [comment]
@numbleroot please sign the CLA?

**Comment by numbleroot** [comment]
Apologies for the delay and thank you both for the feedback. I have signed the CLA and re-run the CI check.

I will attempt to regenerate the documentation pages as described above soon.

**Comment by numbleroot** [comment]
Hi @pcoet, thanks for the follow-up here. I remember I ran into documentation generation issues back when I submitted the PR initially, and tried again with the same result. Some `Signature` can't be imported from `sphinx`. However, the changes I submitted were very minor anyways, so please feel free to go ahead and close this PR. Thank you!

**Pull request closed without merging**
