### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by TylerADavis**
Fix a small typo in example.

Change `Bathc` to `Batch`

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Thanks for the PR! Please also apply the fix to the `md` and `ipynb` files.

**Comment by TylerADavis** [comment]
@fchollet Thanks for pointing those files out. I've now updated them as well.

**Review by fchollet — APPROVED** [review]
LGTM, thank you

**Comment by TylerADavis** [comment]
Great, thank you for your help! It looks like the CI failed, how can it be rerun?

**Comment by fchollet** [comment]
The failure is unrelated, we can merge.

**Comment by TylerADavis** [comment]
Great, thank you for your help!

**Pull request merged**
