### PR TITLE
Fix small typos

### PR DESCRIPTION
**Pull request by Manfred-Madelaine-pro**

### CODE REVIEW

**Comment by Manfred-Madelaine-pro** [comment]
@fchollet - kindly review the PR

**Review by fchollet — COMMENTED** [review]
Please replicate the fixes in the corresponding `.py` and `.ipynb` files.

**Comment by Manfred-Madelaine-pro** [comment]
Hello @fchollet, done.

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
