### PR TITLE
Fix: could not convert string to number

### PR DESCRIPTION
**Pull request by menon92**
@singhva For some records, there are coming empty string

### CODE REVIEW

**Comment by pcoet** [comment]
@menon92 Thanks for the PR, and I apologize for the late response. I think this got overlooked...

You'll need to sign the [CLA](https://cla.developers.google.com/clas) before we can accept contributions from you.

I am not seeing any issues with empty records in this example. Can you explain how to repro?

**Comment by menon92** [comment]
@pcoet I already have CLA 
Screenshot from 2023-08-19 09-06-37

**Comment by pcoet** [comment]
Awesome. I just reran the CLA check, and you're good. Thanks! Can you clarify this?

> I am not seeing any issues with empty records in this example. Can you explain how to repro?

**Comment by menon92** [comment]
@pcoet The issue no more exists

**Comment by pcoet** [comment]
Great. Thanks for the follow up!

**Pull request closed without merging**
