### PR TITLE
Updated the table with links to model and space for CutMix, ConvMixer, TokenLearner examples -  Keras huggingface sprint

### PR DESCRIPTION
**Pull request by harshaUwm163**
the table was not rendered properly earlier. I have updated it.

### CODE REVIEW

**Comment by harshaUwm163** [comment]
I have also added the links to the model and spaces of ConvMixer and TokenLearner examples.

**Comment by fchollet** [comment]
> Continuous integration / black (pull_request)

Please fix!

**Comment by harshaUwm163** [comment]
> > Continuous integration / black (pull_request)
> 
> Please fix!
Hello, I have fixed this! please let me know if any other changes are required!

**Comment by fchollet** [comment]
You seem to be having a rebasing issue. Please rebase on `master`.

**Comment by harshaUwm163** [comment]
Hello, Thanks for the reply! I am currently on the master branch. I pulled changes from the keras-io repo into my forked repo before pushing my changes.

Should I undo that with git reset --hard and push my changes alone?

**Comment by MarkDaoust** [comment]
No. you're doing something like `git merge master` and it's copying commits from master on top or the commits for your PR.

You need to do something like `git rebase master` so it takes just your commits, and replays them on top of master.

After that you'll need to force push the branch to github (or create a new PR).

You need a PR that only has your commits in it.

**Comment by harshaUwm163** [comment]
Hello, thanks for your comments! I have now fixed the merge issue. Please do let me know if everything looks good!!

**Review by fchollet — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
