### PR TITLE
Fix downloading dataset with gdown in deeplabv3_plus.py

### PR DESCRIPTION
**Pull request by victorbug**

### CODE REVIEW

**Comment by fchollet** [comment]
What's the error you're seeing? This code used to work recently.

**Comment by victorbug** [comment]
The error is in 
```
!gdown https://drive.google.com/uc?id=1B9A9UCJYMwTL4oBEo4RZfbMZMaZhKJaz
```
It throw the message:
---
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1B9A9UCJYMwTL4oBEo4RZfbMZMaZhKJaz 

unzip:  cannot find or open instance-level-human-parsing.zip, instance-level-human-parsing.zip.zip or instance-level-human-parsing.zip.ZIP.
---

So I proposed to change that cell to 
``gdown "1B9A9UCJYMwTL4oBEo4RZfbMZMaZhKJaz&confirm=t"`
`

**Comment by fchollet** [comment]
Ok, sounds good! Please replicate the fix in the `md` and `ipynb` files.

**Comment by victorbug** [comment]
> Ok, sounds good! Please replicate the fix in the `md` and `ipynb` files.

Ok, I did what you suggested.. (I modified the files : deeplabv3_plus.ipynb, deeplabv3_plus.py and deeplabv3_plus.md)

The thing is that I tested the command just in the colab file that you provided online (https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/deeplabv3_plus.ipynb), and there it worked well

**Review by fchollet — APPROVED** [review]
Thanks!

**Pull request merged**
