### PR TITLE
Adding accuracy metric to captcha_ocr example

### PR DESCRIPTION
**Pull request by joelsundholm**
I have been struggling to find a way to accurately track the accuracy of my OCR network, and I've finally arrived at something that works. It would have helped me if this example had included an accuracy metric, so feel free to merge my changes if they're acceptable.

### CODE REVIEW

**Comment by joelsundholm** [comment]
@googlebot I signed it!

**Comment by fchollet** [comment]
Thank you for the PR.

@AakashKumarNain what do you think?

**Comment by AakashKumarNain** [comment]
Thanks @joelsundholm for the PR. @fchollet IMO we should be using `editdistance` based metric to evaluate character error rate. What do you say?

**Comment by fchollet** [comment]
>  @fchollet IMO we should be using editdistance based metric to evaluate character error rate. What do you say?

If that's doable, then yes, it seems more useful that character accuracy.

**Comment by rbouadjenek** [comment]
@AakashKumarNain I don't think it makes sense to use `edit distance` for this OCR example as there is no semantic for the words..... IMO Accuracy is still the best thing to do :-)

**Comment by MarkDaoust** [comment]
keras-nlp has an edit-distance metric now:

https://github.com/keras-team/keras-nlp/blob/master/keras_nlp/metrics/edit_distance.py#L22

**Comment by pcoet** [comment]
Hi @joelsundholm, thanks again for the PR. Would you like to update this to use `edit_distance`? If not, we'll go ahead and close the PR.

**Pull request closed without merging**
