### PR TITLE
Fix the number of classes in the Oxford Pets segmentation example

### PR DESCRIPTION
**Pull request by xianlopez**
I've seen the number of classes set in the Oxford Pets image segmentation example is 4, whilst the ground truth there has only three different labels. I imagine this was due to the fact that the labels are 1, 2 and 3, so inputing that directly to the sparse cross entropy loss would require a network with 4 outputs per pixel (as if there were a label 0).

Subtracting 1 to the labels allows to keep the network how it has to be, with three outputs.

### CODE REVIEW

**Review by fchollet — COMMENTED** [review]
Sounds good, please regenerate the autogenerated files via the `add_example` command.

**Comment by xianlopez** [comment]
Amended the commit to avoid black format error.

**Comment by xianlopez** [comment]
I ran the `add_example` function and added a new commit with the autogenerated changes.

**Review by fchollet — APPROVED** [review]
Thank you, LGTM

**Pull request merged**
