### PR TITLE
Uploaded correct images for the functional API

### PR DESCRIPTION
**Pull request by RenuPatelGoogle**
Uploaded correct images for the functional API

### CODE REVIEW

**Comment by fchollet** [comment]
Thank you for the PR. What's the context here?

**Comment by RenuPatelGoogle** [comment]
> Thank you for the PR. What's the context here?

Sorry for the late response. There is a plotted model image architecture mismatch in the output between the latest and older tensorflow versions.

**Comment by fchollet** [comment]
There was a formatting glitch in TF 2.8 that cause cells to be split vertically for the shape display instead of horizontally. It is fixed in recent versions. We should use TF 2.10 or later to generate the images. The images in this PR have the glitch.

**Comment by RenuPatelGoogle** [comment]
> There was a formatting glitch in TF 2.8 that caused cells to be split vertically for the shape display instead of horizontally. It is fixed in recent versions. We should use TF 2.10 or later to generate the images. The images in this PR have the glitch.

@fchollet , Sure Thank you for the update.

**Comment by fchollet** [comment]
In fact, the current images are basically what's intended. Closing the PR

**Pull request closed without merging**
