### PR TITLE
Port [KerasNLP] Transformer Pretraining guide to multi-backend Keras

### PR DESCRIPTION
**Pull request by shivance**
Will close [keras-nlp/#1146](https://github.com/keras-team/keras-nlp/issues/1146)

[Colab](https://colab.research.google.com/drive/1YQRcNoPxeQuNWS9l0d6ujoTDBQbUGX2c?usp=sharing)

cc: @mattdangerw

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
@shivance I think everything here is correct.  Just two quick comments:

1. The colab you link to fails with a runtime error when run.
2. Could you refresh the generated `md` and `ipynb` files?

IIRC the command is:

```
cd scripts
python autogen.py add_guide keras_nlp/transformer_pretraining.ipynb
```
We can easily test the final version from the generated ipynb file.

**Comment by shivance** [comment]
@MarkDaoust this is blocked on [keras-nlp/#1159](https://github.com/keras-team/keras-nlp/issues/1159) as KerasNLP tokenizers don't seem to work with KerasCore. 

Thanks for the input, I can generate ipynb files ones we are done with fixing tokenizers.

**Comment by mattdangerw** [comment]
I think this should be ready. I will try running it today.

**Comment by mattdangerw** [comment]
Needed a few fixes, including one for https://github.com/keras-team/keras-io/issues/1446. Will plan on getting a 0.6.1 KerasNLP release, this can go with it.

**Review by mattdangerw — APPROVED** [review]

**Review by fchollet — APPROVED** [review]
LGTM

**Comment by shivance** [comment]
Awesome !
Thanks @fchollet @mattdangerw , This marks my third contribution to keras-io 😄

**Pull request merged**
