### PR TITLE
Update KerasCV examples to reflect `num_classes` API change

### PR DESCRIPTION
**Pull request by ianstenbit**
This change is being made in [this KerasCV PR](https://github.com/keras-team/keras-cv/pull/1474).

We should wait to merge this into KerasIO until we cut a KerasCV release which includes that change.

### CODE REVIEW

**Review by LukeWood — APPROVED** [review]

**Comment by LukeWood** [comment]
LGTM; you can rebase and remove guides/*

**Comment by ianstenbit** [comment]
Removed guides/* 
This should now be ready to merge along with the 0.5 release.

**Comment by ianstenbit** [comment]
@fchollet PTAL when you have a chance -- thanks!

**Review by jbischof — CHANGES_REQUESTED** [review]
@ianstenbit those densenet examples won't work unless you use `keras_cv.models.legacy.DenseNet()`

Better yet, let's swap a migrated model like EfficientNet.

(don't worry about our landing page; @Haifeng Jin is fixing that)

**Comment by ianstenbit** [comment]
> @ianstenbit those densenet examples won't work unless you use `keras_cv.models.legacy.DenseNet()`
> 
> Better yet, let's swap a migrated model like EfficientNet.
> 
> (don't worry about our landing page; @haifeng Jin is fixing that)

Done -- this is what I get for leaving a PR open for so long that our API changes :)

**Comment by ianstenbit** [comment]
Any ideas on why the CI / docker is failing? The error logs don't seem to exist

**Comment by ianstenbit** [comment]
> Any ideas on why the CI / docker is failing? The error logs don't seem to exist

Nvm it's fixed

**Review by jbischof — APPROVED** [review]
Thank you!

**Review by fchollet — APPROVED** [review]

**Pull request merged**
