### PR TITLE
Update debugging_tips.py

### PR DESCRIPTION
**Pull request by JakeWilds-Vertikal**
simple typo. Not sure if this will create a PR based on where I'm logged in right now. If it doesn't, I'll try to remember to do this from a dev machine when I'm back.

### CODE REVIEW

**Comment by JakeWilds-Vertikal** [comment]
@googlebot I signed it!

**Review by fchollet — CHANGES_REQUESTED** [review]
Thanks for the PR! Please also fix the typo in the generated `ipynb` and `md` files.

**Comment by JakeWilds-Vertikal** [comment]
> Thanks for the PR! Please also fix the typo in the generated `ipynb` and `md` files.

Got those too!

**Review by fchollet — APPROVED** [review]
Thanks!

**Pull request merged**
