### PR TITLE
Fixing critic model to use action output along with state

### PR DESCRIPTION
**Pull request by falaktheoptimist**

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR!

@apoorvnandan can you please take a look?

**Comment by fchollet** [comment]
@apoorvnandan any thoughts on this?

**Comment by apoorvnandan** [comment]
Hi! Sorry I was away from Github for a while. 
@falaktheoptimist Thanks for the PR! The algorithm (or the version of it) implemented here trains the critic to map the state to the total rewards estimate. The critic and actor share the initial layer for brevity. (like an initial embedding layer for the state). They can totally be defined as completely separate networks
```
actor = ActorNetwork()
critic = CriticNetwork()
predicted_action = actor(state)
reward_estimate = critic(state) 
```
that just learn to map the environment state to their respective values. Which is to say, the critic does not directly take into account the predicted action at a particular step in the episode. It processes the state after a sampled action was applied. 

After recording the outputs from both the networks for an entire episode, the critic is updated to produce better estimates (again, from just the state) as compared to the actual rewards received. 

If newer variations of this algorithm consider the predicted probability distribution for the next action as inputs for the critic, I'd be happy to go through the papers. However, the current code serves its purpose of demonstrating the intended algorithm.

**Comment by fchollet** [comment]
@apoorvnandan thanks for the detailed comments.

Based on this feedback, we will not merge this PR at this time.

**Pull request closed without merging**
