### PR TITLE
Migrating Text classification with Transformer example to Keras 3

### PR DESCRIPTION
**Pull request by sitamgithub-MSIT**
This PR changes the [Text classification with Transformer](https://keras.io/examples/nlp/text_classification_with_transformer/) example to keras 3.0 [All Backend].

For example, here is the notebook link provided:
https://colab.research.google.com/drive/1EnnbWbx6eFAWe5NySES-HLtChMx1bSvT?usp=sharing

cc: @divyashreepathihalli @fchollet 

The following describes the Git difference for the changed files:

<details><summary>Changes:</summary>

```
diff --git a/examples/nlp/text_classification_with_transformer.py b/examples/nlp/text_classification_with_transformer.py
index 165f7fe7..7e021ab8 100644
--- a/examples/nlp/text_classification_with_transformer.py
+++ b/examples/nlp/text_classification_with_transformer.py
@@ -10,9 +10,9 @@ Accelerator: GPU
 ## Setup
 """
 
-import tensorflow as tf
-from tensorflow import keras
-from tensorflow.keras import layers
+import keras
+from keras import ops
+from keras import layers
 
 
 """
@@ -35,12 +35,12 @@ class TransformerBlock(layers.Layer):
         self.dropout1 = layers.Dropout(rate)
         self.dropout2 = layers.Dropout(rate)
 
-    def call(self, inputs, training):
+    def call(self, inputs):
         attn_output = self.att(inputs, inputs)
-        attn_output = self.dropout1(attn_output, training=training)
+        attn_output = self.dropout1(attn_output)
         out1 = self.layernorm1(inputs + attn_output)
         ffn_output = self.ffn(out1)
-        ffn_output = self.dropout2(ffn_output, training=training)
+        ffn_output = self.dropout2(ffn_output)
         return self.layernorm2(out1 + ffn_output)
 
 
@@ -58,8 +58,8 @@ class TokenAndPositionEmbedding(layers.Layer):
         self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=embed_dim)
 
     def call(self, x):
-        maxlen = tf.shape(x)[-1]
-        positions = tf.range(start=0, limit=maxlen, delta=1)
+        maxlen = ops.shape(x)[-1]
+        positions = ops.arange(start=0, stop=maxlen, step=1)
         positions = self.pos_emb(positions)
         x = self.token_emb(x)
         return x + positions
(END)
```

### CODE REVIEW

**Comment by sitamgithub-MSIT** [comment]
If the changes are all approved in the .py file. Then I will change the rest of the files accordingly, with updated dates.

**Review by divyashreepathihalli — APPROVED** [review]

**Comment by divyashreepathihalli** [comment]
LGTM! Please generate the .md and .ipynb files

**Comment by sitamgithub-MSIT** [comment]
I think this example is ready with all the necessary updated files. But somehow the cla check is still in progress.

@fchollet Can you look into it?

**Review by fchollet — APPROVED** [review]
LGTM -- thank you! Not sure why the CLA check is frozen, but we can just skip it.

**Pull request merged**
