### PR TITLE
fix install output in md file

### PR DESCRIPTION
**Pull request by pcoet**
It looks like the `autogen` script copied local build output from the notebook into the markdown files. I'm removing this manually. Presumably this will fix the HTML at next publish.

### CODE REVIEW

**Comment by pcoet** [comment]
@fchollet or @MarkDaoust: Can you look at this, when you have a minute? It looks bad on the site. :-(

**Review by MarkDaoust — APPROVED** [review]
Can you edit the pip line in the markdown file:

1. Remove the `!`
2. Add a `-q`

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
(see requested change)

**Comment by pcoet** [comment]
@MarkDaoust Done! Thanks!

**Review by MarkDaoust — APPROVED** [review]

**Pull request merged**
