### PR TITLE
Keras Sprint: added links to model and space for CutMix example at ke…

### PR DESCRIPTION
**Pull request by harshaUwm163**
Huggingface Keras-io Sprint
Added links to the trained model and the space for image classification trained with CutMix data augmentation.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Thanks for the PR! Please also update the `md` and `ipynb` files.

**Comment by harshaUwm163** [comment]
@fchollet I get an error when I run "python autogen.py add_example ../examples/vision/cutmix.py" to generate the ipynb and md files. 

First there is a warning : 
Warning! HDF5 library version mismatched error
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues

Then I get an error and the program stops
[NbConvertApp] ERROR | Kernel died while waiting for execute reply.
[NbConvertApp] Destroying zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object

My libhdf5 version is 1.10.4

Can you please help with fixing this?

**Comment by fchollet** [comment]
I would recommend that you simply replicate your changes across the md and ipynb files without rerunning the command. You seem to have some environment issue.

**Comment by harshaUwm163** [comment]
Thanks for the reply! I have manually added the links to the ipynb and md files. I don't need to create a new PR right?

**Review by fchollet — APPROVED** [review]

**Pull request merged**
