### PR TITLE
huggingface model&spaces

### PR DESCRIPTION
**Pull request by yusyel**
Huggingface Keras-io Sprint:

Just edited `timeseries_weather_forecasting.py` (huggingface model/spaces links) file and Run  python autogen.py add_example timeseries/timeseries_weather_forecasting.py

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by fchollet** [comment]
Please fix style formatting.

**Comment by yusyel** [comment]
> Please fix style formatting.

I have been looking similar merge request. Ummm. I'm not sure which issue you referred.

**Comment by fchollet** [comment]
> Continuous integration / black (pull_request) Failing after 21s — black

See logs.

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by fchollet** [comment]
> Continuous integration / black (pull_request) Failing after 19s — black

The style check is still failing, please fix

**Review by fchollet — APPROVED** [review]
LGTM

**Pull request merged**
