### PR TITLE
Add GCViT example

### PR DESCRIPTION
**Pull request by awsaf49**
This PR will implement and fine-tune Global Context Vision Transfer (GCViT) as mentioned in https://github.com/keras-team/keras/pull/18706

### CODE REVIEW

**Comment by awsaf49** [comment]
cc: @fchollet

**Comment by awsaf49** [comment]
> What Keras version was used to create the weights file?

I used KerasCore at that time for creating weights but can't seem to remember the version. Also, I've tried the code with KerasCore now and getting the same error. I think that during the review process, I made some changes that might have caused it. I'll try to revert each components one by one to check which one is responsible.

**Comment by fchollet** [comment]
Your code is probably fine and it probably never worked with Keras Core. Please try again with Keras 3 at HEAD (built from sources).

**Comment by awsaf49** [comment]
@fchollet, I've tried with Keras 3.0 installing at Head from source with the following code but I am still facing the same issue.
```shell
!git clone https://github.com/keras-team/keras.git
!cd keras && pip install -r requirements.txt
!cd keras && python pip_build.py --install
```
I will try creating the weights in the latest Keras to see if that fixes the problem. Surprisingly old code still runs on the new Keras 3.0 w/o any errors.

**Comment by awsaf49** [comment]
Apologies for the delay, @fchollet. I've generated the weights using the latest version of `Keras`, but I still encountered an error. However, I managed to work around it by loading the weights from a `.keras` model. I have created checkpoints in both `.weights.h5` and `.keras` formats to compare them. Strangely, the `.weights.h5` format throws an error."

**Comment by fchollet** [comment]
> Strangely, the .weights.h5 format throws an error."

What's the error? Can you compare the file structure with the model structure? (printing keys contained in the file and comparing them to model attributes)

**Comment by fchollet** [comment]
> What's the error? Can you compare the file structure with the model structure? (printing keys contained in the file and comparing them to model attributes)

If you're able to provide a reproduction script, please open an issue on the keras repo.

**Review by fchollet — APPROVED** [review]
LGTM, thank you

**Comment by awsaf49** [comment]
> > Strangely, the .weights.h5 format throws an error."
> 
> What's the error? Can you compare the file structure with the model structure? (printing keys contained in the file and comparing them to model attributes)

@fchollet, After rechecking based on your feedback, I discovered that the error occurred because I used Keras to create checkpoints and then attempted to load them using KerasCore. We can confirm this by replacing `.keras` with `.weights.h5` in the merged example.

Thank you for merging this pull request. Happy Holidays!

**Pull request merged**
