### PR TITLE
Share weights between dense layers to make the model permutation invariant

### PR DESCRIPTION
**Pull request by iampat**
The current implementation uses a separate set of dense layers (dense_1 and dense_2) for each instance in the bag. To make the model permutation invariant, each instance in the bag should be treated identically. This can be achieved if the dense layers share the weight between instances.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR -- @MohamadJaber1 please review this change. Thanks!

**Comment by MohamadJaber1** [comment]
Thank you very much for the PR @iampat 
@fchollet I did review it and its indeed correct.

**Review by MohamadJaber1 — APPROVED** [review]

**Comment by iampat** [comment]
@MohamadJaber1 Do I need to add auto-generated files to this diff?

**Comment by MohamadJaber1** [comment]
```
diff --git a/examples/vision/attention_mil_classification.py b/examples/vision/attention_mil_classification.py
index ef3dd13..b41ce06 100644
--- a/examples/vision/attention_mil_classification.py
+++ b/examples/vision/attention_mil_classification.py
@@ -3,7 +3,7 @@ Title: Classification using Attention-based Deep Multiple Instance Learning (MIL
 Author: [Mohamad Jaber](https://www.linkedin.com/in/mohamadjaber1/)
 Date created: 2021/08/16
 Last modified: 2021/11/25
-Description: MIL approach to classify bags of instances and get their individual instance score.
+Description: MIL approach to classify bags of instances and get their individual instance score
 """
 """
 ## Introduction
@@ -320,6 +320,7 @@ def plot(data, labels, bag_class, predictions=None, attention_weights=None):
         print(f"There is no class {bag_class}")
         return
 
+    print(f"The bag class label is {bag_class}")
     for i in range(PLOT_SIZE):
         figure = plt.figure(figsize=(8, 8))
         print(f"Bag number: {labels[i]}")

```

**Comment by MohamadJaber1** [comment]
> ```
> diff --git a/examples/vision/attention_mil_classification.py b/examples/vision/attention_mil_classification.py
> index ef3dd13..b41ce06 100644
> --- a/examples/vision/attention_mil_classification.py
> +++ b/examples/vision/attention_mil_classification.py
> @@ -3,7 +3,7 @@ Title: Classification using Attention-based Deep Multiple Instance Learning (MIL
>  Author: [Mohamad Jaber](https://www.linkedin.com/in/mohamadjaber1/)
>  Date created: 2021/08/16
>  Last modified: 2021/11/25
> -Description: MIL approach to classify bags of instances and get their individual instance score.
> +Description: MIL approach to classify bags of instances and get their individual instance score
>  """
>  """
>  ## Introduction
> @@ -320,6 +320,7 @@ def plot(data, labels, bag_class, predictions=None, attention_weights=None):
>          print(f"There is no class {bag_class}")
>          return
>  
> +    print(f"The bag class label is {bag_class}")
>      for i in range(PLOT_SIZE):
>          figure = plt.figure(figsize=(8, 8))
>          print(f"Bag number: {labels[i]}")
> ```

@iampat please apply to following couple lines update.

**Comment by MohamadJaber1** [comment]
For the auto-generated files, I think you will have to do it so that your changes take affect across the markdown and the notebook files. Thanks again.

**Review by MohamadJaber1 — APPROVED** [review]
Thanks @iampat

**Review by fchollet — APPROVED** [review]
Thanks! Yes, please also commit the changes applied to the md and ipynb files.

**Comment by iampat** [comment]
@fchollet Done!

**Comment by iampat** [comment]
@fchollet @MohamadJaber1 
Do I need to do any further action? 
If I understand it correctly, I don't need to do anything at the moment and someone else should merge this PR.
Am I right?

**Review by fchollet — APPROVED** [review]
Right, everything looks good and we can merge. Thanks!

**Pull request merged**
