### PR TITLE
Fix typos on intro to keras for engineers

### PR DESCRIPTION
**Pull request by pedro823**
### Summary
Fixed typos on the template. 

However, **I wasn't able to run the autogen** to generate all the typo fixes on all the versions.

Does the newly introduced CI do that? If so, we need to change the documentation on autogeneration as well.

### CODE REVIEW

**Comment by fchollet** [comment]
Curious why you couldn't run the command?

**Comment by pedro823** [comment]
@fchollet, my steps were as follows:
1. Created a virtualenv and got a shell over there.
2. Got the list of dependencies that were declared in the header of `autogen.py` and installed them:
```
pip install pygments jinja2 markdown requests mdx_truly_sane_lists
```

3. Running it, I get an error of no module named `sphinx`. 
```
ModuleNotFoundError: No module named 'sphinx'
```

4. So I installed it with `pip install sphinx`, and ran it again. There's the same error with the `black` module, so I installed it as well.

5. At this point, `python3 autogen.py make` starts to do some output. However, at `api/models` we find another missing module, `tensorflow`:

```
...Processing api/models
Traceback (most recent call last):
  File "/Users/raz/web/keras-io/scripts/docstrings.py", line 113, in import_object
    last_object_got = importlib.import_module(".".join(seen_names))
  File "/Users/raz/web/keras-io/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow'
```

Installed it, next.

6. This is when I hit a wall: running it again, it stopped on `api/preprocessing`, which needs more than just module installation.

```
...Processing api/preprocessing
Traceback (most recent call last):
  File "/Users/raz/web/keras-io/scripts/docstrings.py", line 113, in import_object
    last_object_got = importlib.import_module(".".join(seen_names))
  File "/Users/raz/web/keras-io/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow.keras.preprocessing.image_dataset_from_directory'
```

Installing keras didn't help.

#### There are some follow ups to this adventure: ####

- The process of installation could probably use a `Pipfile` from [pipenv](https://pipenv-fork.readthedocs.io/en/latest/). Installation could be as easy as a `pipenv sync`. 
- The process of generating the files should be separated from the process of checking if the code of the files is correct. I didn't stop to read the code, but I assume that's it, since normally you wouldn't need tensorflow & keras to build a static page.
- With that made, we could even go a step further and make the CI verify that `autogen.py` was run before merging the PR by adding a `python autogen.py verify`!

Can I create an issue and start working on those things? :)

**Comment by fchollet** [comment]
We can add a `requirements.txt` to fix these issues.

Also, in your case you edited a `.md` file, but that file is supposed to be autogenerated. You should only edit the `.py` files. I resubmitted a PR copying the fixes in the `.py` file.

**Comment by pedro823** [comment]
@fchollet do you think that should be on a README.md or a CONTRIBUTING.md? That'd help more newcomers.

**Pull request merged**
