### PR TITLE
last modified date fix, machine translation example

### PR DESCRIPTION
**Pull request by mbrotos**
https://github.com/keras-team/keras-io/pull/1254 This PR wrongly stated the year as 2022 instead of 2023 upon the last modification.

### CODE REVIEW

**Review by ianstenbit — APPROVED** [review]
Thanks for the fix! Sending to Francois for approval

**Comment by ianstenbit** [comment]
Also, @mbrotos please take a look at the CLA failure -- contributors to Keras packages will need to be covered under the CLA before changes can be merged. Thanks!

**Comment by mbrotos** [comment]
> Also, @mbrotos please take a look at the CLA failure -- contributors to Keras packages will need to be covered under the CLA before changes can be merged. Thanks!

CLA check passes now. Had to amend the email on the commit. Thanks!

**Review by fchollet — APPROVED** [review]
Thanks!

**Pull request merged**
