### PR TITLE
example added: extending a Image classification with Object detection

### PR DESCRIPTION
**Pull request by krn-sharma**

### CODE REVIEW

**Comment by 8bitmp3** [comment]
Hi, it looks like there are some key issues in this PR—please correct me if I'm wrong:

- The PR proposes to remove all files/content from the Keras website (`keras-team/keras-io`) and adds one file with your example (`classification_to_detection.py`). Maybe you created an empty folder and added your file to it, which may be causing git to interpret that you're removing nearly everything (I've checked your repo: https://github.com/krn-sharma/keras-io). You should only have the "green" diff:

image

- The example appears to have multiple grammar and spelling errors. You can resolve some of them by copying and pasting the Markdown text into a free Google Doc and then clicking on **Tools** > *Spelling and grammar** > **Spelling and grammar check** (wait for a few seconds for the file to be auto-saved in your Google Drive first). Then, I'd suggest that you have someone you know review the text before you commit and push the changes to your repo. It can take hours for reviewers and contributors to check the doc, especially if it contains many basic grammatical errors (such as this sentence: `Convoultion implemention is much more fast than tradition sliding window object detection because it predict the
output of all window in just one inference.`)

Here are some helpful Google guides: writing style: https://developers.google.com/style, "a"/"the" (articles): https://developers.google.com/style/articles, sentence-case capitalization: https://developers.google.com/style/capitalization + anything under **Language and grammar**. Then, check the material under **Punctuation** and **Formatting**. And remember the **General principles** (https://developers.google.com/style/tone). Microsoft also has some awesome material: https://docs.microsoft.com/en-us/style-guide/welcome/ 
👍

I hope this helps!

**Comment by krn-sharma** [comment]
@8bitmp3 Thanks for your feedback. I will review the example.
Documentation for contribution states that to submit only .py file in PR that's why I deleted other files from my fork. Maybe I shouldn't have forked but instead created empty repo. 
I am not sure as I am new to open source contribution but I will check it.
Thank you for taking out your time to review my PR

**Comment by 8bitmp3** [comment]
No worries.

> Documentation for contribution states that to submit only .py file in PR that's why I deleted other files from my fork. Maybe I shouldn't have forked but instead created empty repo.

Yes, by adding a file to the forked repo you don't have to delete everything else—that's how PRs work. Note that the contributing page (https://keras.io/examples/#adding-a-new-code-example) says: _"New examples are added via Pull Requests to the [keras.io repository](https://github.com/keras-team/keras-io). They must be submitted as a `.py` file that follows a specific format."_

**Comment by fchollet** [comment]
@8bitmp3 thanks for the help with the PRs -- much appreciated!

**Comment by fchollet** [comment]
Are you still planning on working on this PR? Should I close it?

**Pull request closed without merging**
