### PR TITLE
Update: Probing_ViTs

### PR DESCRIPTION
**Pull request by ariG23498**
In this PR we change the model links from GDrive to GitHub releases.

CC: @sayakpaul

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks!

**Comment by dicer2000** [comment]
Thank you Sayakpaul.  I'll give it a try later today.

**Review by fchollet — APPROVED** [review]
Great, thanks for the update! Please update the md and ipynb files as well.

**Comment by ariG23498** [comment]
@fchollet I have added the generated files. Over to you now! 🤗

**Review by fchollet — APPROVED** [review]
Thank you!

**Pull request merged**
