### PR TITLE
populating labels outside image extraction loop for efficiency

### PR DESCRIPTION
**Pull request by tagore15**
list of labels can be populated only once. Right now it is being populated while being extracted for each image.

### CODE REVIEW

**Comment by tagore15** [comment]
@googlebot I signed it!

**Review by fchollet — APPROVED** [review]

**Comment by fchollet** [comment]
Thanks for the PR! Please also apply the fix in the `md` and `ipynb` files.

**Comment by fchollet** [comment]
Any update on this?

**Comment by tagore15** [comment]
Sorry for delay. I have updated the PR. Please check now.

**Review by fchollet — APPROVED** [review]
Thanks for the update!

**Pull request merged**
