### PR TITLE
Update generate_images_with_stable_diffusion.py

### PR DESCRIPTION
**Pull request by sayakpaul**
Just two minor changes.

This is such an amazing walkthrough!

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Thanks for the PR! Please replicate the fix in the md and ipynb files.

**Comment by sayakpaul** [comment]
Thanks @fchollet!

May I edit the ipynb and md files directly since the changes are minor?

**Comment by fchollet** [comment]
> May I edit the ipynb and md files directly since the changes are minor?

Absolutely. This is the best solution for any edit small enough that it's possible to manually track the changes.

**Comment by sayakpaul** [comment]
@fchollet ready to merge I guess.

**Comment by fchollet** [comment]
Thank you!

**Pull request merged**
