### PR TITLE
fix typo: output_node -> x

### PR DESCRIPTION
**Pull request by deep-diver**

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by fchollet** [comment]
Can you also update the ipynb and md files?

**Comment by deep-diver** [comment]
@fchollet 

sure! could you guide me where they are?

**Comment by deep-diver** [comment]
@fchollet 

just did!

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Comment by fchollet** [comment]
> This branch has conflicts that must be resolved

Please fix the conflicts (I think it has to do with code formatting)

**Comment by deep-diver** [comment]
@fchollet 

sorry for the delayed response on such a simple issue!
the confict is now resolved.

**Comment by deep-diver** [comment]
@MarkDaoust 

it looks like I need an approval from you as well. Am I correct @fchollet ?

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
