### PR TITLE
Add "accelerator: GPU" to notebooks.

### PR DESCRIPTION
**Pull request by MarkDaoust**
The first commit adds it to the notebook template. 
The second inserts it into all the existing notebooks. 

With this change notebooks will open a Colab GPU instance by default.

WDYT? Or should this be controlled on a notebook-by-notebook basis?

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR! I think this is a good idea overall.

> Or should this be controlled on a notebook-by-notebook basis?

Some notebooks are a better fit for CPU (very small models or examples that don't do any model training).

Some notebooks explicit expect the TPU runtime (those with a TPUStrategy), we could add it to the metadata as well.

**Comment by MarkDaoust** [comment]
> we could add it to the metadata as well.

The block like this at the top of each tutbook?:

"""
Title: Text Extraction with BERT
Author: [Apoorv Nandan](https://twitter.com/NandanApoorv)
Date created: 2020/05/23
Last modified: 2020/05/23
Description: Fine tune pretrained BERT from HuggingFace Transformers on SQuAD.
"""

I'll see if I can figure out how to make that work.

**Comment by MarkDaoust** [comment]
> we could add it to the metadata as well.

Done. I added `Accelerator:` as to the last metadata field to all the tutobooks, and updated the ipynbs to match. 

Any file containing `TPUStrategy` was tagged for `TPU`. Anything without a `.fit` was tagged `None`.  I reviewed the `None`s and upgraded some to GPU.  Switched "intro_to_keras_for_engineers" and "intro_to_keras_for_researchers" to `None`.

**Review by fchollet — APPROVED** [review]
Awesome, thank you so much!

**Pull request merged**
