### PR TITLE
SimCLR example update and fix

### PR DESCRIPTION
**Pull request by beresandras**
I am the original author of the code example, this PR updates it at multiple points:

- fixed the notebook to be valid (fixing https://github.com/keras-team/keras-io/issues/706), it was not parseable because of a comma error since the preprocessing layers were moved to keras.layers (https://github.com/keras-team/keras-io/commit/3a8622d94d7685d84435388a20316a1544d0af5c)
- changed the hyperparameter section's name to hyperparameter setup, because the duplicate titles caused misnavigation on the side menu
- the ALIGN paper's link was changed to link to the abstract instead of the pdf
- one of my github links was incorrect, now it links to the correct repository
- I got feedback, that not setting the training=True flag in the training_step decreased performance in a derivative work, so now I specify it everywhere explicitly. Interestingly, this does not change performance in our case, everything seems to be working the same.

I carefully edited the .py and .md files, and regenerated the notebook. Based on my experiments the performance should be the same, so I did not regenerate the outputs.

Somehow, the online viewer cannot display the .py and .md differences correctly, but they exactly mirror the notebook changes.

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR!

> I got feedback, that not setting the training=True flag in the training_step decreased performance in a derivative work, so now I specify it everywhere explicitly. Interestingly, this does not change performance in our case, everything seems to be working the same.

This cannot affect performance. The layers will always receive a static `training` boolean value (defaults to True, but can be False if the layers are inside a model that is being used in inference mode, e.g. `model.predict()` or `model.evaluate()`). So passing True in this example is functionally equivalent to what would have happened in any case.

Anyhow, it's not harmful to set the value explicitly, either. It's the same.

Just one comment on the PR.

**Comment by beresandras** [comment]
Ah, that is good to know.
Still, it is an improvement that now the encoder is used in inference mode for the linear probing. Omitting that originally was an oversight from my part.

**Comment by beresandras** [comment]
Okay, I have set the training flag to default True.

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
