### PR TITLE
Updated direct link for Custom Objects

### PR DESCRIPTION
**Pull request by RenuPatelGoogle**
Updated direct link to access `Custom Objects` definition by changing #custom-objects to #custom_objects in the given link.

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
LGTM. Can you please also update the corresponding `.md` and `.ipynb` files?

**Comment by fchollet** [comment]
@RenuPatelGoogle any update on the below?

> Can you please also update the corresponding .md and .ipynb files?

**Comment by RenuPatelGoogle** [comment]
> @RenuPatelGoogle any update on the below?
> 
> > Can you please also update the corresponding .md and .ipynb files?
@fchollet, Sorry for delay. I have updated .md and .ipynb files.

**Review by fchollet — APPROVED** [review]
Thank you!

**Pull request merged**
