### PR TITLE
Remove KerasCV and KerasNLP; new structure for KerasHub and KerasTuner

### PR DESCRIPTION
**Pull request by mattdangerw**
- Remove all KerasCV and KerasNLP docs.
- Add redirects so that KerasCV and KerasNLP links point to KerasHub.
- Rework the URL structure so that all KerasHub and KerasTuner content is nested inside the toplevel on the sidebar.
  - `guides/keras_hub/xx` -> `keras_hub/guides/xx`.
  - `api/keras_hub/xx` -> `keras_hub/api/xx`.

Screenshot from 2024-11-25 10-16-58

### CODE REVIEW

**Comment by mattdangerw** [comment]
Not all KerasCV guides have a KerasHub replacement yet. These guides no longer show up on the site, but I've left them in the repo so they can be ported.

**Comment by mattdangerw** [comment]
@divyashreepathihalli KerasCV page will be gone! keras.io/keras_cv will redirect to keras.io/keras_hub

You might want to try rendering locally to get a sense of the new structure.

**Review by fchollet — COMMENTED** [review]
Thanks for the PR! It looks great.

The redirects need to be more granular, especially for KerasCV -- anytime there's a relevant page we can point to, we should. Examples:

- `/api/keras_cv/layers/augmentation/*` - > `/api/layers/preprocessing_layers/image_augmentation/`
- `/api/keras_cv/models/backbones/efficientnet_v2/` -> corresponding API page in KerasHub
- `/api/keras_cv/models/tasks/stable_diffusion/` -> corresponding API page in KerasHub (note, this one has quite a few links that point to it!)
- etc.

Please go over each one by hand and determine what the best page to redirect to is.

**Comment by mattdangerw** [comment]
@fchollet improved the CV links a bit, though a good bit doesn't have a perfect replacement. E.g. for bounding boxes and preprocessing layers in CV I'm just linking to core Keras preprocessing layers.

**Review by fchollet — APPROVED** [review]
Let's ship it

**Pull request merged**
