### PR TITLE
Added EfficientNetV2 docs.

### PR DESCRIPTION
**Pull request by sebastian-sz**
I updated the documentation for EfficientNetV2 models, which were added in [this PR](https://github.com/keras-team/keras/pull/14935).

### CODE REVIEW

**Comment by fchollet** [comment]
This is not yet in 2.7, right? It will appear in 2.8. Therefore we should only update the docs when 2.8 gets released (keras.io does not have version-specific docs at this time). Please comment out the lines for now.

**Comment by sebastian-sz** [comment]
@fchollet 
Commented out the code. 
Sorry, I wasn't sure when to submit this PR with docs. I'll update the PR once 2.8 is released.

**Comment by fchollet** [comment]
We could either merge this now with the commented-out content, or leave the PR open until the 2.8 release, then merge it. Let me know what you think.

**Comment by sebastian-sz** [comment]
I will convert this to draft, so it doesn't attract attention and reconvert (+uncomment) once 2.8 is out.

**Comment by sebastian-sz** [comment]
@fchollet The 2.8 has been released - I have uncommented the docs code.

**Review by fchollet — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
