### PR TITLE
Add HF space and model to Semantic Image Clustering

### PR DESCRIPTION
**Pull request by johko**
This PR contains added HF space and model reference for Semantic Image Clustering.

While running black it also reformatted a line of layers, I don't know if that should stay as black wants it or as it was before.

### CODE REVIEW

**Comment by merveenoyan** [comment]
@johko can you check if version of your black is `black==19.10b0`?

**Comment by fchollet** [comment]
Please see style formatting (see logs)

**Comment by johko** [comment]
I reverted the style formatting and updated my black. In the newer version it does not complain, about it anymore.

**Review by fchollet — APPROVED** [review]
Looks good, thanks! Please also update the `md` and `ipynb` files.

**Comment by johko** [comment]
Sorry for the late reply on this, I was on an extended holiday. 
I uploaded the generated files but there seems to be some cla issue related to a huggingface account seemingly involved and I don't exactly know where that comes from. Do you have any idea @merveenoyan ?

**Comment by fchollet** [comment]
Did you actually sign the CLA with the email you used to sign the commits in the PR?

**Comment by johko** [comment]
I found the issue regarding the CLA - apparently while following a tutorial on Sagemaker usage with huggingface I somewhere changed my global git credentials accidentally, which lead to the error here. I'm working on fixing it now.

**Comment by johko** [comment]
@fchollet it should be good now :)

**Review by fchollet — APPROVED** [review]
LGTM

**Pull request merged**
