### PR TITLE
Planets_and_Moons_Dataset_AI_in_Space - Add New

### PR DESCRIPTION
**Pull request by emirhanai**
Hello,
I added my Planets and Moons Dataset and AI in Space Software's second version.
Thanks!

### CODE REVIEW

**Review by fchollet — CHANGES_REQUESTED** [review]
Thanks for the PR! There are multiple files in this PR, so before we can review please remove all files except the `.py` file of the example you want to submit in this PR.

**Comment by emirhanai** [comment]
> Thanks for the PR! There are multiple files in this PR, so before we can review please remove all files except the `.py` file of the example you want to submit in this PR.

Yes i removed (Only Planet .py, .ipynb, .md and IMG folder remain)

**Comment by fchollet** [comment]
> Yes i removed (Only Planet .py, .ipynb, .md and IMG folder remain)

Please follow the instructions in the README and take a look at the `.py` file for other examples to get an idea of how to format the code.

**Comment by emirhanai** [comment]
> > Yes i removed (Only Planet .py, .ipynb, .md and IMG folder remain)
> 
> Please follow the instructions in the README and take a look at the `.py` file for other examples to get an idea of how to format the code.

Yes i followed after then this generated by automatic from jupyter library.

**Pull request closed without merging**
