### PR TITLE
Upgrade Cyclegan to Keras 3 (with Tensorflow backend)

### PR DESCRIPTION
**Pull request by pksX01**
This PR caters the upgradation of Cycelgan example to Keras 3 (with Tensorflow backend) from Keras 2.

## Changes
- Since weight load format is changes in Keras 3, pre-trained weight could not be loaded. Hence, changed the epochs to 90 (as equivalent to original training).
- Replaced Tensorflow specific operations with Keras backend-agnostic equivalents wherever possible.

### CODE REVIEW

**Comment by pksX01** [comment]
@sachinprasadhs could you please review this PR

**Review by fchollet — COMMENTED** [review]
The conversion looks good! Please add the autogenerated .md and .ipynb files.

**Review by fchollet — APPROVED** [review]
Looking good! Please add the generated files.

**Comment by pksX01** [comment]
@fchollet added ipynb and md files

**Review by fchollet — COMMENTED** [review]
Thank you! It seems the training logs are very large and are taking up a lot of space in the `.md`, can you erase them by hand? They don't need to be rendered.

**Comment by pksX01** [comment]
> Thank you! It seems the training logs are very large and are taking up a lot of space in the `.md`, can you erase them by hand? They don't need to be rendered.

@fchollet Removed training logs.

**Review by fchollet — APPROVED** [review]
Thank you! LGTM

**Pull request merged**
